daysUntilStale: 45
daysUntilClose: false

exemptLabels:
  - "WIP"
  - "discussion"
  - "information"
  - "not stale"
  - "package request"
  - "tracker"
  - "untriaged"

exemptAssignees: true

markComment: false

only: issues

staleLabel: stale

