daysUntilStale: 45
daysUntilClose: 14

exemptLabels:
  - "WIP"
  - "discussion"
  - "not stale"
  - "package request"

markComment: >
  This issue/PR has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

staleLabel: wontfix

