name: Build bootstrap archives (t-1)

on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/build_archives.yml
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64
          # - arm
          # - i686
          # - x86_64
    steps:
      - name: Git clone
        uses: actions/checkout@v4
      # - name: Patch
      #   run: ./patch-repo.sh
      - name: Create bootstrap archive
        run: |
          ./scripts/setup-ubuntu.sh
            sudo apt install ninja-build
            sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(aspnetcore|cabal-|dotnet-|ghc-|libmono|php)') \
              firefox google-chrome-stable microsoft-edge-stable mono-runtime-common monodoc-manual ruby
            sudo apt autoremove -yq
            sudo rm -fr /opt/hostedtoolcache /usr/share/dotnet /usr/share/swift
            NDK=$ANDROID_NDK_LATEST_HOME ANDROID_HOME=$ANDROID_SDK_ROOT ./scripts/build-bootstraps.sh  --architectures ${{ matrix.arch }}
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap-archives-${{ matrix.arch }}-${{ github.sha }}
          path: "*.zip"
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch bootstrap archives
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./
      - name: Create new tag
        id: get_tag
        run: |
          new_tag="bootstrap-$(date "+%Y.%m.%d")"
          existing_tag_revision=$(git tag | grep "$new_tag" | sort -r | head -n 1 | cut -d- -f3 | cut -dr -f2)
          if [ -n "$existing_tag_revision" ]; then
            tag_rev=$((existing_tag_revision + 1))
          else
            tag_rev=1
          fi
          new_tag="${new_tag}-r${tag_rev}+apt-android-7"
          git tag "$new_tag"
          git push --tags
          echo "tag_name=$new_tag" >> $GITHUB_OUTPUT
      - name: Publish bootstrap zips to GitHub release
        uses: termux/upload-release-action@v4.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.zip"
          file_glob: true
          release_name: "Bootstrap archives for Termux application"
          tag: ${{ steps.get_tag.outputs.tag_name }}
          checksums: sha256,sha512,md5
