name: Packages

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/packages-all.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"
    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1000
    - name: Free additional disk space on host
      run: |
        sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
          liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual powershell ruby
        sudo apt autoremove -yq
        sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
    - name: Patch
      run: ./patch-repo.sh
    - name: Build
      run: |
        ./scripts/run-docker.sh ./build-all.sh -a ${{ matrix.target_arch }} -i -o ./debs
        mv ./_buildall-${{ matrix.target_arch }}/buildorder.txt ./debs/built_packages.txt
        tar cf artifacts/debs-${{ matrix.target_arch }}-${{ github.sha }}.tar debs
    - name: Checksums for built *.deb files
      run: |
        find debs -type f -name "*.deb" -exec sha256sum "{}" \; | sort -k2
    - name: Store *.deb files
      uses: actions/upload-artifact@v2
      with:
        name: termux-packages-${{ github.sha }}
        path: ./artifacts
  upload:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Get *.deb files
      uses: actions/download-artifact@v2
      with:
        name: termux-packages-${{ github.sha }}
        path: ./
    - name: Setup ssh key and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOST_ENTRY }}" >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-add - <<< "${{ secrets.SSHKEY }}"
    - name: Upload to vhn.vn
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        # Zip the deb archives to only do one transfer to the repo.
        # This makes it easier to parse it, we can run one update job
        # instead of one for each arch on the server.
        archive="termux-packages-${{ github.sha }}.zip"
        zip $archive debs-*-${{ github.sha }}.tar
        sftp -P ${{ secrets.PORT }} ${{ secrets.USER }}@vhn.vn <<EOF
          put $archive /debs/
        EOF
